# Site settings
name: Diana Ricketts
email: dianadricketts@gmail.com
#canonical_url: https://edwinexemplar.com
keywords: "Software Engineer, JavaScript, HTML, CSS, SQL, Node, Web Development, Full Stack"
skills: "Junior Developer in Fayetteville, AR"
baseurl:

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# You should replace these with your social networks, of course. :)
social:
  - title: linkedin
    url: https://www.linkedin.com/in/diana-ricketts-a31a33189
  - title: github
    url: https://github.com/dricketts0
  - title: twitter
    url: https://twitter.com/DianaRicketts3
    
# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: ACE2CE
  primary-rgb: "172, 226, 206"
  secondary: 024D3C
  secondary-dark: 43574F
  section-tout: eaf1f1



# Build settings
markdown: kramdown
permalink: pretty
